name: ai-trends-py312
channels:
  - conda-forge
  - defaults
dependencies:
  - tqdm
  - pyyaml
  - numpy
  - polars
  - fastembed
  - arxiv
  - python=3.12
  - ipykernel
  - spacy
  - scikit-learn
  - sentence-transformers
  - matplotlib
  
